McDonalds/McDonalds/Controllers/EmployeesController.cs
using Domain;
using McDonalds.EmployeeFacade;
using Microsoft.AspNetCore.Mvc;

namespace McDonalds.Controllers;

public class EmployeesController : Controller
{
    private readonly EmployeeFacade.EmployeeFacade EmployeeFacade;
    
    public EmployeesController()
    {
        EmployeeFacade = new EmployeeFacade.EmployeeFacade();
    }
    
    public IActionResult Index()
    {
        return View(EmployeeFacade.GetAll());
    }
    
    [HttpGet]
    //[Route("Employees")]
    public IActionResult AddEmployee()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult AddEmployee(Employee employee)
    {
        EmployeeFacade.AddEmployee(employee);
        return RedirectToAction("Index");
    }

    [HttpGet]
    //[Route("Employees/{id:int}")]
    public IActionResult EditEmployee(int id)
    {
        var employee = EmployeeFacade.GetAll().FirstOrDefault(e => e.Id == id);
        return View(employee);
    }
    
    [HttpPost]
    public IActionResult EditEmployee(Employee employee)
    {
        EmployeeFacade.UpdateEmployee(employee);
        return RedirectToAction("Index");
    }

    public IActionResult RemoveEmployee(int id)
    {
        EmployeeFacade.RemoveEmployee(id);
        return RedirectToAction("Index");
    }
}

McDonalds/McDonalds/Controllers/MacMenuController.cs
using System.Reflection;
using Domain.Entites;
using McDonalds.MacMenuBuilder;
using McDonalds.OrderFactory;
using McDonalds.Views;
using Microsoft.AspNetCore.Mvc;

namespace McDonalds.Controllers;

public class MacMenuController : Controller
{
    // GET
    public IActionResult Index()
    {
        var builders = Assembly.GetExecutingAssembly().GetTypes()
            .Where(t => t.IsClass && !t.IsAbstract && t.Namespace == "McDonalds.MacMenuBuilder")
            .Where(t => typeof(MacMenuBuilder.MacMenuBuilder).IsAssignableFrom(t))
            .Select(Activator.CreateInstance)
            .Cast<MacMenuBuilder.MacMenuBuilder>()
            .ToList();

        return View(builders);
    }
}

McDonalds/McDonalds/Controllers/OrdersController.cs
using DataAccess;
using Domain;
using Domain.Entites;
using McDonalds.EmployeeFacade;
using McDonalds.Models;
using McDonalds.Models.Employees;
using McDonalds.OrderFactory;
using Microsoft.AspNetCore.Mvc;

namespace McDonalds.Controllers;

public class OrdersController : Controller
{
    private readonly McDonaldsDbContext _context;

    public OrdersController()
    {
        _context = McDonaldsDbContext.Context;  
    }
    public IActionResult Index()
    {
        return RedirectToAction("CreateOrders");
    }
    
    [HttpGet]
    [Route("orders")]
    public IActionResult CreateOrders(string difficulty = "LowDifficulty")
    {
        OrderFactory.OrderFactory factory = GetFactoryByDifficulty(difficulty);
        var orders = new List<Order>();
        
        for (int i = 0; i < 5; i++)
        {
            var order = CreateSingleOrder(factory);
            ProcessOrder(order);
            orders.Add(order);
        }
        
        return View("Index", orders);
    }

    private Order CreateSingleOrder(OrderFactory.OrderFactory factory)
    {
        List<Burger> burgerOrder = factory.CreateBurgers();
        List<Drink> drinkOrder = factory.CreateDrinks();
        
        var order = new Order
        {
            OrderNumber = new Random().Next(1, 1000),
            Burgers = burgerOrder,
            Drinks = drinkOrder,
            Description = string.Empty
        };

        return order;
    }
    private void ProcessOrder(Order order)
    {
        var mediator = new OrderMediator.OrderMediator();
        var cook = new Cook(GetFreeWorker(EmployeeRole.Cook), mediator);
        var cashier = new Cashier(GetFreeWorker(EmployeeRole.Cashier), mediator);
        
        mediator.AddWorker(cashier);
        mediator.AddWorker(cook);
        
        mediator.HandleOrder(order, cashier);
        mediator.HandleOrder(order, cook);
    }
    
    private string GetFreeWorker(EmployeeRole role)
    {
        var employeesNumber = _context.Employees.Count(e => e.Role == role);
        var randomNumber = new Random().Next(1, employeesNumber + 1);
        
        return _context.Employees.Where(e => e.Role == role)
            .Skip(randomNumber - 1)
            .Take(1)
            .Select(e => e.FullName)
            .FirstOrDefault() ?? string.Empty;
    }
    
    private OrderFactory.OrderFactory GetFactoryByDifficulty(string difficulty)
    {
        OrderFactory.OrderFactory factory;
            
        if (difficulty == "LowDifficulty")
            factory = new LowDifficultyFactory();
        else if (difficulty == "MediumDifficulty")
            factory = new MediumDifficultyFactory();
        else if (difficulty == "HardDifficulty")
            factory = new HardDifficultyFactory();
        else
            factory = new LowDifficultyFactory();

        ViewBag.Difficulty = difficulty;
        return factory;
    }
}

McDonalds/McDonalds/Views/Shared/_Layout.cshtml
@using Domain
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - McDonalds</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/McDonalds.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            @{
                var mcDonalds = McDonaldsDepartment.GetInstance(); 
            }
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@mcDonalds.Name @mcDonalds.Country</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="MacMenu" asp-action="Index">Mac Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - McDonalds - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

McDonalds/McDonalds/Views/Shared/_NotificationBanner.cshtml
<div class="notification-banner">
    <p>Це банер сповіщень. Тут може бути ваше повідомлення або інформація.</p>
</div>

<style>
    .notification-banner {
        padding: 10px;
        margin-bottom: 20px;
    }
    
    Warning {
        background-color: #ffeeba;
        border: 1px solid #ffc107;
    }
    
    Error {
        background-color: #f8d7da;
        border: 1px solid #dc3545;
    }
    
    Success {
        background-color: #d4edda;
        border: 1px solid #28a745;
    }
</style>